In [48]:
import pandas as pd
import numpy as np

# import plotting libraries
import matplotlib.pyplot as plt
%matplotlib inline 

import seaborn as sns
sns.set(style="white", color_codes=True)
sns.set(font_scale=1.5)
from sklearn.model_selection import train_test_split

In [49]:
from sklearn.neighbors import KNeighborsClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import  MultinomialNB

In [50]:
from sklearn.feature_extraction.text import CountVectorizer

In [51]:
!pip install wordcloud

In [59]:
from wordcloud import WordCloud, STOPWORDS 

In [60]:
pd.set_option('max_colwidth', 400)

In [61]:
from email.mime.text import MIMEText
sms = pd.read_csv("sms.tsv", header=None, sep='\t',names=['label', 'message'])

In [62]:
sms.sample(10)

label                                                                                                                                                                message
5363   ham                                                                                                                     I think your mentor is , but not 100 percent sure.
427    ham                                                                                                                                            aathi..where are you dear..
868   spam                  PRIVATE! Your 2003 Account Statement for 07808 XXXXXX shows 800 un-redeemed S. I. M. points. Call 08719899217 Identifier Code: 41685 Expires 07/11/04
2505   ham       Hello, my boytoy! I made it home and my constant thought is of you, my love. I hope your having a nice visit but I can't wait till you come home to me ...*kiss*
4415   ham                                                                How stupid to say that i challenge god.You dont think at all on what i write instead you respond immed.
2701   ham  Feb  &lt;#&gt;  is "I LOVE U" day. Send dis to all ur "VALUED FRNDS" evn me. If 3 comes back u'll gt married d person u luv! If u ignore dis u will lose ur luv 4 Evr
5545   ham                                                                                                                          Hi its in durban are you still on this number
3795   ham                                                                                           Short But Cute: "Be a good person, but dont try to prove it.." .Gud noon....
4128   ham                                                                                                                                                 Sorry, I'll call later
4935   ham                                                                                                                                      Hey do you want anything to buy:)

In [63]:
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

to see if there is class imbalance

In [64]:
# convert label to a numerical variable
sms['label_num'] = sms.label.map({'ham': 0, 'spam': 1})

In [65]:
sms.head(10)

label                                                                                                                                                           message  label_num
0   ham                                                   Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...          0
1   ham                                                                                                                                     Ok lar... Joking wif u oni...          0
2  spam       Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's          1
3   ham                                                                                                                 U dun say so early hor... U c already then say...          0
4   ham                                                                                                     Nah I don't think he goes to usf, he lives around here though          0
5  spam               FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv          1
6   ham                                                                                     Even my brother is not like to speak with me. They treat me like aids patent.          0
7   ham  As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune          0
8  spam     WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.          1
9  spam        Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030          1

In [66]:
X = sms.message
y = sms.label_num

In [67]:
from sklearn.model_selection import train_test_split

In [68]:
# split X and y into training ans testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1) 

In [69]:
X_train.shape, X_test.shape

((4179,), (1393,))

In [70]:
vect = CountVectorizer()

In [71]:
vect.fit(X_train, y_train)

CountVectorizer()

In [72]:
X_train_dtm = vect.transform(X_train)

In [73]:
X_train_dtm.shape

(4179, 7456)

In [74]:
np.set_printoptions(linewidth=140, edgeitems=12)

In [75]:
X_train_dtm.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0,

In [76]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_dtm, y_train)

KNeighborsClassifier(n_neighbors=3)

In [77]:
X_test_dtm = vect.transform(X_test)   

y_pred     = knn.predict(X_test_dtm)

In [78]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [79]:
accuracy_score(y_test, y_pred)

0.927494615936827

In [80]:
confusion_matrix(y_test, y_pred)

array([[1208,    0],
       [ 101,   84]], dtype=int64)

In [81]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96      1208
           1       1.00      0.45      0.62       185

    accuracy                           0.93      1393
   macro avg       0.96      0.73      0.79      1393
weighted avg       0.93      0.93      0.92      1393



#### Try logistic regression

In [82]:
model = LogisticRegression()

model.fit(X_train_dtm, y_train)

LogisticRegression()

In [83]:
X_test_dtm = vect.transform(X_test)

In [84]:
y_pred = model.predict(X_test_dtm)

In [85]:
accuracy_score(y_test, y_pred)

0.9877961234745154

In [86]:
confusion_matrix(y_test, y_pred)

array([[1207,    1],
       [  16,  169]], dtype=int64)

In [87]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1208
           1       0.99      0.91      0.95       185

    accuracy                           0.99      1393
   macro avg       0.99      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393



#### try naive bayes algo

In [88]:
from sklearn.naive_bayes import MultinomialNB

In [89]:
nb = MultinomialNB()

In [90]:
nb.fit(X_train_dtm, y_train)

MultinomialNB()

In [91]:
np.set_printoptions(edgeitems=10)

In [92]:
X_train_dtm.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 

In [93]:
X_train_dtm.shape

(4179, 7456)

In [94]:
y_pred_class = nb.predict(X_test_dtm)

accuracy_score(y_test, y_pred_class)


0.9885139985642498

In [95]:
confusion_matrix(y_test, y_pred_class)

array([[1203,    5],
       [  11,  174]], dtype=int64)

In [96]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 140)  # or 199

In [97]:
sms.sample(20)

label                                                                                                                                      message  label_num
76     ham                                                                    Thats cool. i am a gentleman and will treat you with dignity and respect.          0
2527   ham                                                                                               Do u noe how 2 send files between 2 computers?          0
2863  spam                                                                                         Adult 18 Content Your video will be with you shortly          1
245    ham                                                                                                        U don't remember that old commercial?          0
4228   ham                                                                                                              Buy one egg for me da..please:)          0
2012   ham  Do whatever you want. You know what the rules are. We had a talk earlier this week about what had to start happening, you showing respon...          0
124    ham                                                                                         I am going to sao mu today. Will be done only at 12           0
3116   ham                                                                                                             I wait 4 ü inside da car park...          0
4596   ham                                                                                                               Yo sorry was in the shower sup          0
4637   ham                                                                                                                   K k pa Had your lunch aha.          0
3944   ham                                   I got a call from a landline number. . . I am asked to come to anna nagar . . . I will go in the afternoon          0
3218   ham                                                                                                     Come to mahal bus stop.. &lt;DECIMAL&gt;          0
1485   ham                                                                                                                       Sorry, I'll call later          0
905    ham                                                         We're all getting worried over here, derek and taylor have already assumed the worst          0
4431   ham                                                                                                  Yar lor... How u noe? U used dat route too?          0
713   spam                                                                                                        08714712388 between 10am-7pm Cost 10p          1
3327   ham                                                                                         Huh so fast... Dat means u havent finished painting?          0
3663   ham        What are you doing in langport? Sorry, but I'll probably be in bed by 9pm. It sucks being ill at xmas! When do you and go2sri lanka?           0
1434   ham                                                                              You intrepid duo you! Have a great time and see you both soon.           0
2952   ham                                                                                                             Hey now am free you can call me.          0

In [98]:
# vectorizer tuning
import nltk
from nltk.corpus import stopwords
from string import punctuation

# Stemmer
from nltk.stem import PorterStemmer
porter = PorterStemmer()

# lemmatizing
from nltk.stem import WordNetLemmatizer
wnl = WordNetLemmatizer()

In [99]:
# Stopwords from stopwords-json
# https://raw.githubusercontent.com/6/stopwords-json/master/dist/en.json

stopwords_json = {"en":["a","a's","able","about","above","according","accordingly","across","actually","after","afterwards","again","against","ain't","all","allow","allows","almost","alone","along","already","also","although","always","am","among","amongst","an","and","another","any","anybody","anyhow","anyone","anything","anyway","anyways","anywhere","apart","appear","appreciate","appropriate","are","aren't","around","as","aside","ask","asking","associated","at","available","away","awfully","b","be","became","because","become","becomes","becoming","been","before","beforehand","behind","being","believe","below","beside","besides","best","better","between","beyond","both","brief","but","by","c","c'mon","c's","came","can","can't","cannot","cant","cause","causes","certain","certainly","changes","clearly","co","com","come","comes","concerning","consequently","consider","considering","contain","containing","contains","corresponding","could","couldn't","course","currently","d","definitely","described","despite","did","didn't","different","do","does","doesn't","doing","don't","done","down","downwards","during","e","each","edu","eg","eight","either","else","elsewhere","enough","entirely","especially","et","etc","even","ever","every","everybody","everyone","everything","everywhere","ex","exactly","example","except","f","far","few","fifth","first","five","followed","following","follows","for","former","formerly","forth","four","from","further","furthermore","g","get","gets","getting","given","gives","go","goes","going","gone","got","gotten","greetings","h","had","hadn't","happens","hardly","has","hasn't","have","haven't","having","he","he's","hello","help","hence","her","here","here's","hereafter","hereby","herein","hereupon","hers","herself","hi","him","himself","his","hither","hopefully","how","howbeit","however","i","i'd","i'll","i'm","i've","ie","if","ignored","immediate","in","inasmuch","inc","indeed","indicate","indicated","indicates","inner","insofar","instead","into","inward","is","isn't","it","it'd","it'll","it's","its","itself","j","just","k","keep","keeps","kept","know","known","knows","l","last","lately","later","latter","latterly","least","less","lest","let","let's","like","liked","likely","little","look","looking","looks","ltd","m","mainly","many","may","maybe","me","mean","meanwhile","merely","might","more","moreover","most","mostly","much","must","my","myself","n","name","namely","nd","near","nearly","necessary","need","needs","neither","never","nevertheless","new","next","nine","no","nobody","non","none","noone","nor","normally","not","nothing","novel","now","nowhere","o","obviously","of","off","often","oh","ok","okay","old","on","once","one","ones","only","onto","or","other","others","otherwise","ought","our","ours","ourselves","out","outside","over","overall","own","p","particular","particularly","per","perhaps","placed","please","plus","possible","presumably","probably","provides","q","que","quite","qv","r","rather","rd","re","really","reasonably","regarding","regardless","regards","relatively","respectively","right","s","said","same","saw","say","saying","says","second","secondly","see","seeing","seem","seemed","seeming","seems","seen","self","selves","sensible","sent","serious","seriously","seven","several","shall","she","should","shouldn't","since","six","so","some","somebody","somehow","someone","something","sometime","sometimes","somewhat","somewhere","soon","sorry","specified","specify","specifying","still","sub","such","sup","sure","t","t's","take","taken","tell","tends","th","than","thank","thanks","thanx","that","that's","thats","the","their","theirs","them","themselves","then","thence","there","there's","thereafter","thereby","therefore","therein","theres","thereupon","these","they","they'd","they'll","they're","they've","think","third","this","thorough","thoroughly","those","though","three","through","throughout","thru","thus","to","together","too","took","toward","towards","tried","tries","truly","try","trying","twice","two","u","un","under","unfortunately","unless","unlikely","until","unto","up","upon","us","use","used","useful","uses","using","usually","uucp","v","value","various","very","via","viz","vs","w","want","wants","was","wasn't","way","we","we'd","we'll","we're","we've","welcome","well","went","were","weren't","what","what's","whatever","when","whence","whenever","where","where's","whereafter","whereas","whereby","wherein","whereupon","wherever","whether","which","while","whither","who","who's","whoever","whole","whom","whose","why","will","willing","wish","with","within","without","won't","wonder","would","wouldn't","x","y","yes","yet","you","you'd","you'll","you're","you've","your","yours","yourself","yourselves","z","zero"]}

In [100]:
stopwords_json_en = set(stopwords_json['en'])
stopwords_nltk_en = set(stopwords.words('english'))
stopwords_punct   = set(punctuation)

In [101]:
# Combine the stopwords. Its a lot longer so I'm not printing it out...
stoplist_combined = set.union(stopwords_json_en, stopwords_nltk_en, stopwords_punct)

In [102]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [103]:
vect = TfidfVectorizer(stop_words=stoplist_combined, 
                       token_pattern='(?u)\\b[a-zA-Z]{3,}\\b')

In [104]:
vect

TfidfVectorizer(stop_words={'!', '"', '#', '$', '%', '&', "'", '(', ')', '*',
                            '+', ',', '-', '.', '/', ':', ';', '<', '=', '>',
                            '?', '@', '[', '\\', ']', '^', '_', '`', 'a', "a's", ...},
                token_pattern='(?u)\\b[a-zA-Z]{3,}\\b')

In [105]:
vect.fit(X_train)                     # create the fitted vocabulary
X_train_dtm = vect.transform(X_train) # create the document-term matrix

C:\Users\19144\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:396: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['mon'] not in stop_words.
  warnings.warn(


In [106]:
# Number of rows = number of training samples,
# number of columns = features
X_train_dtm.shape

(4179, 5943)

In [107]:
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1393x5943 sparse matrix of type '<class 'numpy.float64'>'
	with 7238 stored elements in Compressed Sparse Row format>

In [108]:

nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)

y_pred_class = nb.predict(X_test_dtm)
accuracy_score(y_test, y_pred_class)

0.9691313711414213